version: 2 
jobs: 
  build:
    docker: 
      - image: "circleci/golang:1.12"
    working_directory: /go/src/github.com/camposss/tech-talks/http-server
    steps: 
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - run: 
          name: "Build Docker Image"
          command: |
            # source $BASH_ENV
            TAG=$CIRCLE_WORKFLOW_ID
            make docker TAG=$TAG
      - run: 
          name: "Login and Push Docker Image"
          command: |
            TAG=$CIRCLE_WORKFLOW_ID
            make push TAG=$TAG

            
